name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Congrats! 🎉 This is your first issue, we will review it as soon as possible. If you are able to implement this feature or fix the bug, don't be shy and start commiting"
        pr-message: "Thank you! 🤗 We will review your code as soon as possible. Stay tuned for updates!"
